---
name: Release

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flit
            - name: Prepare release
              run: |
                  (cd tooling && flit install)
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  python -m tts_tooling .
                  git show
            - name: Test packaging
              run: |
                  flit build
              if: "github.event_name == 'pull_request'"
            - name: Push changeset
              run:
                  git push
              if: "github.event_name == 'push'"
            - name: Publish to pypi
              env:
                  FLIT_INDEX_URL:  https://upload.pypi.org/legacy/
                  FLIT_USERNAME: "__token__"
                  FLIT_PASSWORD: ${{ secrets.PROD_PYPI_TOKEN }}
              run: |
                  flit publish
              if: "github.event_name == 'push'"
